### ISSUE TITLE
Build with VS is complete broken

### ISSUE THREAD

**Issue by pps83** [google/pik#44]
It used to build a few months ago (if anybody was willing to fiddle with cmake), but current pik isn't even close to building on VS.

Can you please provide proper instructions on how to build pik on VS, or better, simply add proper VS projects instead of dealing with cmake mess.

**Comment by jan-wassenberg** [comment]
Hi, thanks for reaching out. We don't officially support CMake nor MSVC, but occasionally we can help make them work :)

I just created native MSVC build files. Getting it to build required fairly widespread changes to the code, which I'll push soon.

**Comment by pps83** [comment]
Thanks Jan,
I can help with VS specific changes to make it build. You can find builtin clz/ctz emulation in [my gist](https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0).

**Comment by jan-wassenberg** [comment]
Thank you offering to help! I've added ifdefs inside the bits.h functions, code changes are not a problem and we avoid the unsigned long vs long-long workarounds.

Interesting that MSVC needs a cast of nullptr - seemed to work OK on 15.3 (2017). Which version needs the cast?

Update: build succeeds but round-trip test fails. I need to integrate my code changes into our dev environment, ensure they're OK, then investigate further.

**Comment by pps83** [comment]
> Interesting that MSVC needs a cast of nullptr - seemed to work OK on 15.3 (2017). Which version needs the cast? (From your PR I'm assuming 2015?)

Correct, I'm using 2015.

Also, IMO it's better to completely avoid ctzl/clzl variants and use ll versions for 64 bit numbers. My gitst adds overload for c++ to make them work with 64-bit numbers even though unsigned long is always 32-bit on windows.

**Comment by jan-wassenberg** [comment]
Made some progress: updated CMakeLists.txt and pushed the code changes + MSVC build files,
but there are two issues remaining:

1) guetzli directory has butteraugli_comparator/entropy_encode, which also exist in pik/.
Suggest renaming those to guetzli_* because MSBuild can't handle name collisions despite multiple directories.

2) Either remove all calls to SIMD_NONE specializations in simd/dispatch.h, or add another
source file that #defines SIMD_ENABLE 0 and #includes af_edge_preserving_filter.cc.

After fixing these, I saw our round-trip test fails when built with MSVC.
Unfortunately I am unable to investigate further; we only support building on Linux at the moment.

**Comment by pps83** [comment]
After pulling latest I get these errors:

```
1>C:\pik\pik.cc(208): error C2672: 'pik::dispatch::Run': no matching overloaded function found
1>C:\pik\pik.cc(208): error C2893: Failed to specialize function template 'unknown-type pik::dispatch::Run(const int,Func &&,Args &&...)'
...
1>C:\pik\quantizer.cc(892): error C2075: 'pik::AddDequantizeDC::<lambda_1a348e291128beae9ad5acdbaf349894>::mul_dc': array initialization requires a brace-enclosed initializer list

```

**Comment by jan-wassenberg** [comment]
I think the first one is the af_edge_preserving_filter issue mentioned above (2).
For the second, it seems to work with the free MSVC 2017 (15.3). Is updating an option?

**Comment by eustas** [comment]
Thank you for your contributions. This project is no longer under development and will be archived soon.
If the issue is still relevant, please report in in JPEG XL project.
