### PR TITLE
Fix compilation on Clang 3.4

### LINKED ISSUE #25: Code does not compile with Clang 3.4
The first batch of errors (though not the only ones):

```
clang++ -c  -std=c++11 -Wall -O3 -fPIC -mavx2 -mfma -mlzcnt -mbmi2 -I. -Wno-sign-compare -I/usr/include/libpng12   cpik.cc -o obj/cpik.o
In file included from cpik.cc:15:
In file included from ./image_io.h:27:
./image.h:155:28: error: use of undeclared identifier '__builtin_assume_aligned'
    return static_cast<T*>(PIK_ASSUME_ALIGNED(row, 64));
                           ^
./compiler_specific.h:102:40: note: expanded from macro 'PIK_ASSUME_ALIGNED'
#define PIK_ASSUME_ALIGNED(ptr, align) __builtin_assume_aligned((ptr), (align))
                                       ^
In file included from cpik.cc:15:
In file included from ./image_io.h:27:
./image.h:162:28: error: use of undeclared identifier '__builtin_assume_aligned'
    return static_cast<T*>(PIK_ASSUME_ALIGNED(row, 64));
                           ^
./compiler_specific.h:102:40: note: expanded from macro 'PIK_ASSUME_ALIGNED'
#define PIK_ASSUME_ALIGNED(ptr, align) __builtin_assume_aligned((ptr), (align))
                                       ^
In file included from cpik.cc:15:
In file included from ./image_io.h:27:
./image.h:174:48: error: use of undeclared identifier '__builtin_assume_aligned'
    return static_cast<uint8_t * PIK_RESTRICT>(PIK_ASSUME_ALIGNED(p, 64));
                                               ^
./compiler_specific.h:102:40: note: expanded from macro 'PIK_ASSUME_ALIGNED'
#define PIK_ASSUME_ALIGNED(ptr, align) __builtin_assume_aligned((ptr), (align))
                                       ^
In file included from cpik.cc:15:
In file included from ./image_io.h:27:
./image.h:178:54: error: use of undeclared identifier '__builtin_assume_aligned'
    return static_cast<const uint8_t * PIK_RESTRICT>(PIK_ASSUME_ALIGNED(p, 64));
                                                     ^
./compiler_specific.h:102:40: note: expanded from macro 'PIK_ASSUME_ALIGNED'
#define PIK_ASSUME_ALIGNED(ptr, align) __builtin_assume_aligned((ptr), (align))
                                       ^
4 errors generated.
make: *** [obj/cpik.o] Error 1
```

### PR DESCRIPTION
**Pull request by ruuda**
Fixes #25.

All of these preprocessor defines are a bit ugly, but for now this at least makes it compile.

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Thanks for reporting and fixing these! For the record, we'll push to github via MOE.
